// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Data;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240409184103_addComents")]
    partial class addComents
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ToDoList.Data.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id_Todo_Item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_User")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Todo_Item");

                    b.HasIndex("Id_User");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id_Todo_Item = 1,
                            Description = "descripcion 1",
                            Id_User = 1,
                            Title = "titulo 1"
                        },
                        new
                        {
                            Id_Todo_Item = 2,
                            Description = "descripcion 2",
                            Id_User = 2,
                            Title = "titulo 2"
                        });
                });

            modelBuilder.Entity("ToDoList.Data.Entities.User", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_User");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id_User = 1,
                            Address = "San juan 1129",
                            Email = "belen.linera@gmail.com",
                            Name = "belen"
                        },
                        new
                        {
                            Id_User = 2,
                            Address = "corrientes 1323",
                            Email = "florencia.colombo@gmail.com",
                            Name = "florencia"
                        });
                });

            modelBuilder.Entity("ToDoList.Data.Entities.TodoItem", b =>
                {
                    b.HasOne("ToDoList.Data.Entities.User", "User")
                        .WithMany("TodoItems")
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDoList.Data.Entities.User", b =>
                {
                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
